import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import type { Customer, Product } from "@/types";

// ─── Types ───────────────────────────────────────────────────────────────────

export type ProductWithStock = Product & { stock: number };

export interface LineItem {
  _id: string;
  product_id: string;
  product_name: string;
  brand: string | null;
  shade_number: string | null;
  pack_size: string | null;
  quantity: number;
  unit_price: number;
  discount_pct: number;
  gst_rate: number;
  gst_amount: number;
  line_total: number;
  stock_available: number;
  room_area: string | null;
  house_mapping_id: string | null;
}

export interface CreateBillPayload {
  customer_id: string;
  date: string;
  due_date: string | null;
  payment_method: string;
  notes: string | null;
  paid_amount: number;
  items: LineItem[];
}

export interface CreateInvoiceResult {
  success: boolean;
  bill_id: string;
  bill_number: string;
  total: number;
  paid_amount: number;
  pending: number;
  status: string;
}

// ─── Pure helpers ─────────────────────────────────────────────────────────────

export function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

export function calcRow(item: LineItem): LineItem {
  const base = item.quantity * item.unit_price;
  const discountAmt = base * (item.discount_pct / 100);
  const taxable = base - discountAmt;
  const gst_amount = round2(taxable * (item.gst_rate / 100));
  const line_total = round2(taxable + gst_amount);
  return { ...item, gst_amount, line_total };
}

// ─── Product search (with stock) ─────────────────────────────────────────────

export function useProductSearch(search: string) {
  return useQuery({
    queryKey: ["product-search", search],
    queryFn: async (): Promise<ProductWithStock[]> => {
      let q = (supabase as any)
        .from("products")
        .select("*, inventory(quantity)")
        .eq("is_active", true);
      if (search) {
        q = q.or(`name.ilike.%${search}%,brand.ilike.%${search}%,sku.ilike.%${search}%,shade_name.ilike.%${search}%`);
      }
      q = q.order("name").limit(30);
      const { data, error } = await q;
      if (error) throw new Error(error.message);
      type Raw = Product & { inventory?: { quantity: number }[] | null };
      return ((data ?? []) as Raw[]).map((p) => ({
        ...p,
        stock: p.inventory?.[0]?.quantity ?? 0,
      }));
    },
    placeholderData: (prev: ProductWithStock[] | undefined) => prev,
  });
}

// ─── Customer search (lightweight for picker) ────────────────────────────────

export type CustomerSummary = Pick<Customer, "id" | "name" | "phone" | "city">;

export function useCustomerSearch(search: string) {
  return useQuery({
    queryKey: ["customer-search-bill", search],
    queryFn: async (): Promise<CustomerSummary[]> => {
      let q = supabase
        .from("customers")
        .select("id, name, phone, city");
      if (search) {
        q = q.or(`name.ilike.%${search}%,phone.ilike.%${search}%`);
      }
      q = q.order("name").limit(20);
      const { data, error } = await q;
      if (error) throw new Error(error.message);
      return (data ?? []) as CustomerSummary[];
    },
    placeholderData: (prev: CustomerSummary[] | undefined) => prev,
  });
}

// ─── Create bill ──────────────────────────────────────────────────────────────
//
// Multi-step atomic operation (all via Supabase directly):
//   1. Calculate totals from line items
//   2. Insert bill header (bill_number auto-generated by DB trigger)
//   3. Insert all bill_items and record inventory deductions
//   4. Insert payment record if paid_amount > 0
//   5. Update customer denormalised fields
//
// On success, invalidates all affected React Query caches.

export function useCreateBill() {
  const qc = useQueryClient();

  return useMutation({
    mutationFn: async (payload: CreateBillPayload): Promise<CreateInvoiceResult> => {
      // ── 1. Calculate totals ────────────────────────────────────────────────
      const computed = payload.items.map(calcRow);
      const subtotal = round2(computed.reduce((s, i) => s + i.quantity * i.unit_price * (1 - i.discount_pct / 100), 0));
      const totalTax = round2(computed.reduce((s, i) => s + i.gst_amount, 0));
      const total    = round2(computed.reduce((s, i) => s + i.line_total, 0));
      const paid     = round2(Math.min(payload.paid_amount, total));

      const status: "paid" | "partially_paid" | "unpaid" =
        paid <= 0        ? "unpaid"
        : paid >= total  ? "paid"
        : "partially_paid";

      const pm = payload.payment_method as "cash" | "upi" | "card" | "credit" | "bank_transfer" | "cheque";

      // ── 2. Insert bill header ──────────────────────────────────────────────
      const { data: billData, error: billError } = await (supabase as any)
        .from("bills")
        .insert({
          customer_id:    payload.customer_id,
          date:           payload.date,
          due_date:       payload.due_date,
          payment_method: pm,
          notes:          payload.notes,
          subtotal,
          discount:       0,
          tax_rate:       0,
          tax:            totalTax,
          total,
          paid_amount:    paid,
          status,
        })
        .select()
        .single();

      if (billError) throw new Error(billError.message);
      const bill = billData as { id: string; bill_number: string };

      // ── 3. Insert bill_items and deduct inventory ──────────────────────────
      const itemRows = computed.map((item) => ({
        bill_id:      bill.id,
        product_id:   item.product_id,
        product_name: item.product_name,
        brand:        item.brand,
        shade_number: item.shade_number,
        pack_size:    item.pack_size,
        quantity:     item.quantity,
        unit_price:   item.unit_price,
        discount:     round2(item.quantity * item.unit_price * (item.discount_pct / 100)),
        gst_rate:     item.gst_rate,
        gst_amount:   item.gst_amount,
        total:        item.line_total,
      }));

      const { error: itemsError } = await (supabase as any).from("bill_items").insert(itemRows);
      if (itemsError) throw new Error(itemsError.message);

      // Deduct inventory for each item using the RPC
      for (const item of computed) {
        await (supabase as any).rpc("record_stock_movement", {
          p_product_id:    item.product_id,
          p_type:          "sale",
          p_quantity_change: -item.quantity,
          p_reference_type: "bill",
          p_reference_id:   bill.id,
        });
      }

      // ── 4. Insert payment if paid_amount > 0 ──────────────────────────────
      if (paid > 0) {
        const payMethod = (["cash","upi","bank_transfer","cheque","card","other"].includes(pm)
          ? pm : "cash") as "cash" | "upi" | "bank_transfer" | "cheque" | "card" | "other";
        await (supabase as any).from("payments").insert({
          customer_id:    payload.customer_id,
          bill_id:        bill.id,
          amount:         paid,
          payment_method: payMethod,
          payment_date:   payload.date,
        });
      }

      // ── 5. Update customer denormalised fields ─────────────────────────────
      const { data: cust } = await (supabase as any)
        .from("customers")
        .select("total_purchase_amount, total_purchase_count, pending_balance")
        .eq("id", payload.customer_id)
        .single();
      type CustRow = { total_purchase_amount: number; total_purchase_count: number; pending_balance: number } | null;

      if ((cust as CustRow)) {
        const c = cust as NonNullable<CustRow>;
        await (supabase as any).from("customers").update({
          last_purchase_date:    payload.date,
          total_purchase_amount: (c.total_purchase_amount ?? 0) + total,
          total_purchase_count:  (c.total_purchase_count  ?? 0) + 1,
          pending_balance:       (c.pending_balance       ?? 0) + (total - paid),
        }).eq("id", payload.customer_id);
      }

      // ── 6. Save paint shades for items that have one ───────────────────────
      const shadesPayload = computed
        .filter((i) => i.shade_number)
        .map((i) => ({
          customer_id: payload.customer_id,
          brand:       i.brand,
          shade_name:  i.shade_number!,
          room_area:   i.room_area,
          house_mapping_id: i.house_mapping_id,
          applied_date: payload.date,
        }));
      if (shadesPayload.length > 0) {
        await (supabase as any).from("customer_paint_shades").insert(shadesPayload);
      }

      return {
        success:     true,
        bill_id:     bill.id,
        bill_number: bill.bill_number,
        total,
        paid_amount: paid,
        pending:     total - paid,
        status,
      };
    },

    onSuccess: (result) => {
      void qc.invalidateQueries({ queryKey: ["bills"] });
      void qc.invalidateQueries({ queryKey: ["customers"] });
      void qc.invalidateQueries({ queryKey: ["inventory"] });
      void qc.invalidateQueries({ queryKey: ["payments"] });
      void qc.invalidateQueries({ queryKey: ["customer-paint-shades"] });
      void qc.invalidateQueries({ queryKey: ["product-search"] });
      void qc.invalidateQueries({ queryKey: ["dashboard"] });
      toast.success(`Invoice ${result.bill_number} created`);
    },

    onError: (err: Error) => toast.error(err.message),
  });
}

// ─── Quick-create customer (inline modal) ────────────────────────────────────

export function useQuickCreateCustomer() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (values: { name: string; phone: string }): Promise<CustomerSummary> => {
      const { data, error } = await (supabase as any)
        .from("customers")
        .insert(values)
        .select("id, name, phone, city")
        .single();
      if (error) throw new Error(error.message);
      return data as CustomerSummary;
    },
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["customer-search-bill"] });
      void qc.invalidateQueries({ queryKey: ["customers"] });
    },
    onError: (err: Error) => toast.error(err.message),
  });
}
